### ISSUE TITLE
Devkit Bundle Command Constructor Errors Break 'pimcore:list'

### ISSUE THREAD

**Issue by clarkedb** [DivanteLtd/pimcore-devkit#24]
**Bug description**
When trying to run the Pimcore CLI command `pimcore:list`, the PimcoreDevkitBundle throws an error in the constructors of command classes, specifically the `BricksUpdateCommand` class.

**Steps to reproduce the behavior:**
1. Go to Pimcore project root
2. Run `bin/console pimcore:list`
3. See Uncaught Symfony FatalThrowableError: `Too few arguments to function PimcoreDevkitBundle\Command\BricksUpdateCommand::__construct(), 0 passed in /.../getBricksUpdateCommandService.php on line 9 and at least 2 expected in /.../Command/BricksUpdateCommand.php:40`

**Expected behavior**
Display a comprehensive list of commands from Pimcore and Pimcore Bundles.

**Additional context**
I've noticed the same errors occur when trying to run `bin/console devkit:bricks:update` or `bin/console devkit:classes:update`.

This is in Pimcore 6.0.5 built on Symfony 4.3.3. I have pimcore-devkit v. 0.79 installed as a dependency of [divanteltd/pimcore-magento2-bridge](https://github.com/DivanteLtd/pimcore-magento2-bridge).

**Comment by bramalho** [comment]
@kubaplas PR #23 fixes this issue

We are removing classes/bricks update for the time being
