### ISSUE TITLE
Pimcore 6.8 bundle not working

### ISSUE THREAD

**Issue by rajesh17692** [DivanteLtd/pimcore-devkit#35]
When trying to install below on pimcore 6.8 receiving the below error on both browser and CLI
composer require divanteltd/pimcoredevkit

Not able to execute any command even bin/console

![image](https://user-images.githubusercontent.com/32155962/96445572-bd148900-122d-11eb-81e5-3f31613cf37e.png)
![image](https://user-images.githubusercontent.com/32155962/96445611-d1588600-122d-11eb-82db-282d718e168f.png)

**Comment by prugala** [comment]
Hi @rajesh17692 could you update bundle version to 'dev-master' in your project and check if the problem still exists? I've fixed services.yml file for Wysiwyg services.

**Comment by rajesh17692** [comment]
Now receiving below issue

![image](https://user-images.githubusercontent.com/32155962/96454725-e76c4380-1239-11eb-9bfc-0b3123d88329.png)

**Comment by rajesh17692** [comment]
I Updated the composer as suggested

![image](https://user-images.githubusercontent.com/32155962/96454836-0b2f8980-123a-11eb-9b92-9e0e86363414.png)

**Comment by prugala** [comment]
@rajesh17692 sorry, please try again. Now should be ok.

**Comment by rajesh17692** [comment]
Now what I need to change as a composer is already updated in the previous reply please provide steps which now I have to perform.

**Comment by prugala** [comment]
Run `composer update divanteltd/pimcoredevkit`

**Comment by rajesh17692** [comment]
Received nothing to be installed or updated
![image](https://user-images.githubusercontent.com/32155962/96499096-945eb480-126a-11eb-9af9-f6c7a0a525ff.png)

**Comment by prugala** [comment]
OK so please remove composer.lock and vendor folder, then run `composer install` again.

**Comment by rajesh17692** [comment]
ok let me check with that also

**Comment by rajesh17692** [comment]
Now it's working

The changes you made will impact any features of pimcoredevkit ?

**Comment by prugala** [comment]
No, I've fixed registration of services only. Tomorrow I will create new tag `v0.12.7` with fixes so I will can change version in your composer from dev-master on ^0.12.

**Comment by rajesh17692** [comment]
Are you aware of how to use workflow from GUI using the below bundle
composer require youwe/workflow-gui dev-master

If you know please share the video as I am not getting how to use this form GUI I. I want to create a workflow for products.

Thanks in advance.

**Comment by kubaplas** [comment]
@rajesh17692 this question should be asked on Workflow gui's repo
